version: "2.4"

services:

  core:
    image: laravelvpnadmin/api-core
    restart: unless-stopped
    ports:
    - 80:80
    volumes:
    - ./logs/api-core:/var/log/apache2
    - ./sites/api-core/storage:/app/storage
    - ./sites/api-core/bootstrap/cache:/app/bootstrap/cache
#    - ../api-core:/app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  queue:
    image: laravelvpnadmin/api-core
    restart: unless-stopped
    environment:
    - CONTAINER_ROLE=queue
    user: www-data
    volumes:
    - ./logs/api-core:/var/log/apache2
    - ./sites/api-core/storage:/app/storage
    - ./sites/api-core/bootstrap/cache:/app/bootstrap/cache
#    - ../api-core:/app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  scheduler:
    image: laravelvpnadmin/api-core
    restart: unless-stopped
    environment:
    - CONTAINER_ROLE=scheduler
    user: www-data
    volumes:
    - ./logs/api-core:/var/log/apache2
    - ./sites/api-core/storage:/app/storage
    - ./sites/api-core/bootstrap/cache:/app/bootstrap/cache
#    - ../api-core:/app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    restart: unless-stopped
    image: redis:5
    ports:
    - 127.0.0.1:6379:6379
    volumes:
    - ./databases/redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mariadb:
    restart: unless-stopped
    image: mariadb:10
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: vpnadmin
      MYSQL_USER: vpnadmin_user
      MYSQL_PASSWORD: vpnadmin_pass
    volumes:
      - ./databases/mariadb:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootroot
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
